zstyle :plugin:fast-syntax-highlighting theme "solarized"
typeset -g FAST_THEME_NAME="solarized"
: ${FAST_HIGHLIGHT_STYLES[solarizeddefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[solarizedunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedreserved-word]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedalias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedsuffix-alias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedbuiltin]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedfunction]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedcommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedprecommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedcommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[solarizedhashed-command]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedpath]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[solarizedpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[solarizedglobbing]:=fg=9,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedglobbing-ext]:=fg=13}
: ${FAST_HIGHLIGHT_STYLES[solarizedhistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedsingle-hyphen-option]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[solarizeddouble-hyphen-option]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[solarizedback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[solarizedsingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizeddouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizeddollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedback-or-dollar-double-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[solarizedback-dollar-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[solarizedassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[solarizedredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[solarizedcomment]:=fg=10,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedvariable]:=fg=9}
: ${FAST_HIGHLIGHT_STYLES[solarizedmathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedmathnum]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[solarizedmatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[solarizedassign-array-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[solarizedfor-loop-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[solarizedfor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedfor-loop-separator]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedhere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedhere-string-text]:=fg=15}
: ${FAST_HIGHLIGHT_STYLES[solarizedhere-string-var]:=fg=15,bg=cyan}
: ${FAST_HIGHLIGHT_STYLES[solarizedsecondary]:=default}
: ${FAST_HIGHLIGHT_STYLES[solarizedcase-input]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedcase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedcase-condition]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[solarizedcorrect-subtle]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[solarizedincorrect-subtle]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[solarizedsubtle-separator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizedsubtle-bg]:=bg=0}
: ${FAST_HIGHLIGHT_STYLES[solarizedpath-to-dir]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[solarizedbracket-level-1]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedbracket-level-2]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedbracket-level-3]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[solarizedglobal-alias]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[solarizedsubcommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedsingle-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizeddouble-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[solarizeddouble-paren]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedoptarg-string]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[solarizedoptarg-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[solarizedrecursive-base]:=fg=magenta}
