#! /bin/sh

# Aliases
alias album_edit='beet edit "$(beet list | cut -d'-' -f'1,2' | sort -u | fzf -m | cut -d'-' -f2)"'
alias archw='ddgr --url-handler linkhandler \!arch'
alias ddgr='ddgr --url-handler linkhandler'
alias fopen='setsid nohup xdg-open "$(fzf --reverse --multi --border)"'
alias mutt='neomutt'
alias song_edit='beet edit "$(beet list | fzf | cut -d'-' -f3)"'
alias yt='ddgr --url-handler linkhandler \!yt'
alias yt-audio='yt-dlp -x --split-chapters'

alias neofetch='neofetch --block_range 0 15'

# Colourise command outputs
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls --color=auto'

# Specify config files
alias extract_url='extract_url -c $HOME/.config/extract_urlview/config'

# XDG Data
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget/wget-hsts"'

# Modify power commands
alias poweroff='poweroff --no-wall'
alias reboot='reboot --no-wall'

# Kitty aliases
if [ "$TERM" = 'kitty' ] || [ "$TERM" = xterm-kitty ] || [ "$TERMINFO" = /usr/lib/kitty/terminfo ]; then
	alias im='kitty +kitten icat'
fi
