#! /bin/sh

# Aliases
alias mutt='neomutt'
alias wik='vim -c "VimwikiIndex"'
alias ddgr='ddgr --url-handler linkhandler'
alias yt='ddgr --url-handler linkhandler \!yt'
alias archw='ddgr --url-handler linkhandler \!arch'
alias album_edit='beet edit "$(beet list | cut -d'-' -f'1,2' | sort -u | fzf -m | cut -d'-' -f2)"'
alias song_edit='beet edit "$(beet list | fzf | cut -d'-' -f3)"'
alias fopen='setsid nohup xdg-open "$(fzf --reverse --multi --border)"'

alias neofetch='neofetch --block_range 0 15'

# Colourise command outputs
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls --color=auto'

# Specify config files
alias extract_url='extract_url -c $HOME/.config/extract_urlview/config'
