#! /usr/bin/env zsh
function diary() {
		# Run over standard options
		local opts
		local wiki_no; declare -i wiki_no
		while getopts ityn: opts
		do
				# Take the wiki number
				case $opts in
						n) wiki_no=$OPTARG
				esac
				case $opts in
						i)
								nvim -c "VimwikiDiaryIndex $wiki_no"; return;;
						t)
								nvim -c "VimwikiMakeTomorrowDiaryNote $wiki_no"; return;;
						y)
								nvim -c "VimwikiMakeYesterdayDiaryNote $wiki_no"; return;;
				esac
				echo $OPTARG
		done
		# Catch arguments only
		if [[ -z $opts ]]; then
				case $1 in
						'')
								nvim -c "VimwikiMakeDiaryNote"; return;;
						*)
								date -d "$1" > /dev/null &&
										nvim ~/Documents/Notes/diary/$(date -d "$1" +%Y-%m-%d).md;;
				esac
		fi
}
