#! /usr/bin/env zsh
function diary() {
		# Run over standard options
		local opts
		local nval; declare -i nval
		while getopts ityn: opts
		do
				case $opts in
						n) nval=$OPTARG
				esac
				case $opts in
						i)
								vim -c "VimwikiDiaryIndex $nval"; return;;
						t)
								vim -c "VimwikiMakeTomorrowDiaryNote $nval"; return;;
						y)
								vim -c "VimwikiMakeYesterdayDiaryNote $nval"; return;;
				esac
				echo $OPTARG
		done
		# Catch arguments only
		if [[ -z $opts ]]; then
				case $1 in
						'')
								vim -c "VimwikiMakeDiaryNote"; return;;
						*)
								date -d "$1" > /dev/null &&
										vim ~/Documents/Notes/diary/$(date -d "$1" +%Y-%m-%d).md;;
				esac
		fi
}
