#! /bin/sh
# Fallback file preview script for use with vifm
# Uses the file utility and highlight
FILE="$1"
FILETYPE=$(file "$FILE")

# Check for symlinks
if [ -L "$FILE" ]; then
	# echo "$FILETYPE" |
		# fmt -s
		ls -l --color=always "$FILE" | awk '{print $9,$10,$11}'
# Check for plain text
elif echo "$FILETYPE" | grep -q 'ASCII'; then
	highlight -O ansi -S text -s solarized-dark "$FILE" |
		fmt -s || echo "$FILETYPE"
# Give up and print the output from file
else
	echo "$FILETYPE" |
		fmt -s
fi
