directory: ~/Music            # The default library root directory.
art_filename: cover          # The default name for album art
paths:
  default: $albumartist/$album%aunique{}/$disc-$track $title
bell: yes
per_disc_numbering: yes
plugins: convert fetchart edit mpdupdate extrafiles missing mbsync duplicates playlist replaygain
fetchart:
  minwidth: 1000

edit:
  itemfields: track title artist disc album
  albumfields: album albumartist disctotal

extrafiles:
  patterns:
    all: '*.*'

convert:
  dest: ~/.local/share/beets/convert/
  copy_album_art: yes
  embed: yes
  never_convert_lossy_files: yes
  hardlink: true
  command: convert_gapless_mp3 $source $dest
  extension: mp3


playlist:
  auto: no
  relative_to: ~/Music
  playlist_dir: ~/.local/share/mpd/playlists

replaygain:
  backend: ffmpeg
  peak: sample

  ui:
    color: yes
    colors:
      text_success: green
      text_warning: yellow
      text_error: red
      text_highlight: red
      text_highlight_minor: lightgray
      action_default: turquoise
      action: blue
