local o = vim.o
o.number = true
o.tabstop = 4
o.shiftwidth = 4
o.termguicolors = true
o.mouse = "a"
o.omnifunc = "syntaxcomplete#Complete"
o.cursorline = true
o.scrolloff = 5
o.undofile = true
o.inccommand = "nosplit"
o.list = true
o.foldcolumn = 'auto:1'
o.foldlevel=99
o.foldlevelstart=99
