local o = vim.o
o.number = true
o.tabstop = 4
o.shiftwidth = 4
o.termguicolors = true
o.mouse = "a"
o.omnifunc = "syntaxcomplete#Complete"
o.cursorline = true
o.scrolloff = 5
o.undofile = true
o.inccommand = "nosplit"
o.list = true
o.foldlevel=99
o.foldlevelstart=99
o.viewoptions = "folds,cursor"
local spelldir = vim.fn.stdpath("data") .. '/spell/'
vim.fn.mkdir(spelldir, "p")
local spellfile = spelldir .. "en.utf-8.add"
o.spellfile =  spellfile
